### ATTENTION:
### This file is auto generated by `generate-unique-file.rb`. Please, don't edit this file.
### If you want to edit this code, please refer to files in scripts/ folder

require 'pry'

def source_paths
  [File.expand_path(File.join(File.dirname(__FILE__), 'template_files'))]
end

module GrappiTemplate

  BASE_DIR = File.expand_path(File.join(File.dirname(__FILE__), 'template_files'))

  module Helpers
    protected def app_name
      Rails.application.class.parent_name.underscore
      # ARGV[1].underscore rescue 'application'
    end

    protected def copy_directory(src, dest = nil)
      new_src = File.join(BASE_DIR, src)
      directory new_src, dest.nil? ? src : dest
    end

    def copy_file_to(file_src, file_dest = nil)
      copy_file File.join(BASE_DIR, file_src), file_dest || file_src
    end
  end
end


module GrappiTemplate
  module Minimal

    include Helpers

    module_function
    def run_minimal_template!
      say "Removing useless Rails files"
      remove_minimal_files

      say "Copying required files for minimal template"
      copy_minimal_files

      say "Injecting configurations on specific files"
      setup_minimal_configurations

      say "Configurating gems"
      setup_minimal_gems

      say "Configurating routes"
      setup_minimal_routes

      say "Applying final minimal template"
      finish_minimal_template

      say "Finished applying minimal template"
    end

    ### ==== Remove files from generated Rails project and copy template files ====

    # remove all rails crap
    def remove_minimal_files
      remove_dir 'app/controllers'
      remove_dir 'app/helpers'
      remove_dir 'app/assets'
      remove_dir 'test' # rails new -T dont create this directory, otherwise delete it
      remove_file 'app/views/layouts/application.html.erb'
    end

    def copy_minimal_files
      copy_minimal_concerns
      copy_minimal_configs
      copy_minimal_configs_other
      copy_minimal_deploy
      copy_minimal_docs
      copy_minimal_initializers
      copy_minimal_libs
      copy_minimal_locales
      copy_minimal_helpers
      copy_minimal_http_api_routes
      copy_minimal_mailers
      copy_minimal_rake_tasks
      copy_minimal_services
      copy_minimal_specs
    end

    def copy_minimal_concerns
      copy_file_to File.join('models', 'concerns', 'accessable.rb'), File.join('app', 'model', 'concerns', 'accessable.rb')
    end

    def copy_minimal_configs
      copy_directory File.join('config', 'app_config')
      copy_file_to File.join('config', 'application.yml')
      copy_file_to File.join('config', 'config.rb')
      copy_file_to File.join('config', 'puma.rb')
    end

    def copy_minimal_configs_other
      copy_file_to 'Procfile'
      copy_file_to 'contributors.txt'
      copy_file_to '.rspec'
      copy_file_to '.editorconfig'
    end

    def copy_minimal_deploy
      copy_file_to 'Capfile'
      copy_file_to File.join('config', 'heroku-deploy.yml')
      copy_directory 'deploy', File.join('config', 'deploy')
    end

    def copy_minimal_docs
      copy_directory 'docs', 'docs'
    end

    def copy_minimal_initializers
      [
        File.join('initializers', 'ams.rb'), # active model serializer
        File.join('initializers', 'app_config.rb'),
        File.join('initializers', 'loaders.rb'),
        File.join('initializers', 'new_relic_grape.rb'),
        File.join('initializers', 'nifty_services_setup.rb'),
        File.join('initializers', 'rollbar.rb'),
        File.join('initializers', 'services_setup.rb')
      ].each do |file|
        copy_file_to file, File.join('config', 'initializers', file)
      end
    end

    def copy_minimal_libs
      copy_file_to File.join('lib', 'rake_heroku_deployer.rb')
    end

    def copy_minimal_locales
      copy_file_to File.join('config', 'locales', 'service_response.en.yml')
      copy_file_to File.join('config', 'locales', 'service_response.pt-BR.yml')
    end

    def copy_minimal_helpers
      [
        File.join('api', 'helpers', 'application_helpers.rb'),
        File.join('api', 'helpers', 'paginate_helpers.rb'),
        File.join('api', 'v1', 'helpers', 'application_helpers.rb')
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end

    def copy_minimal_http_api_routes
      [
        File.join('api', 'base.rb'),
        File.join('api', 'v1', 'base.rb'),
        File.join('api', 'v1', 'routes', 'heartbeat.rb')
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end

    def copy_minimal_mailers
      copy_file_to File.join('mailers', 'application_mailer.rb'), File.join('app', 'mailers', 'application_mailer.rb')
      copy_directory File.join('views', 'layouts', 'mailer.html.erb'), File.join('app', 'views', 'layouts', 'mailer.html.erb')
    end

    def copy_minimal_rake_tasks
      copy_directory 'rake_tasks', File.join('lib', 'tasks')
    end

    # In minimal setup only system services are necessary
    def copy_minimal_services
      copy_directory File.join('services', 'v1', 'system'), File.join('lib', 'services', 'v1', 'system')
    end

    def copy_minimal_specs
      copy_spec_config
    end

    def copy_spec_config
      copy_file_to File.join('spec', 'spec_helper.rb')
      copy_file_to File.join('spec', 'rails_helper.rb')
    end

    ### ==== Configuration setup starts ====

    def setup_minimal_configurations
      configure_application_rb
      configure_config_ru
      configure_environments
      configure_seeds_rb
    end

    def configure_application_rb
      inject_into_class "config/application.rb", 'Application' do
        <<-CODE
    # we're dropping not necessarily middlewares for API HTTP request processing
    config.middleware.delete "ActionDispatch::Static"
    config.middleware.delete "ActionDispatch::Cookies"
    config.middleware.delete "ActionDispatch::Session::CookieStore"
    config.middleware.delete "ActionDispatch::Flash"
    config.middleware.delete "Rack::MethodOverride"

    # Since it's an API, we dont need to generate any kind of asset or views(only for mailers)
    config.generators do |g|
      # g.template_engine nil
      g.stylesheets     false
      g.javascripts     false
      g.assets          false
      g.helper          false
    end

    # Add lib folder to autoload paths (to auto reload code when changed)
    config.paths.add File.join(Rails.root, 'lib'), glob: File.join('**', '*.rb')
    config.autoload_paths << Rails.root.join('lib')

    # load Grape API files
    config.autoload_paths += Dir.glob(File.join(Rails.root, 'app', 'grape', '{**,*}'))
    config.paths.add File.join(Rails.root, 'app', 'grape'), glob: File.join('**', '*.rb')
        CODE
      end
    end

    def configure_config_ru
      # This file is used by Rack-based servers to start the application.
      append_to_file "config.ru" do
      <<-CODE.strip_heredoc
      require 'rack/cors'

      use Rack::Cors do
        # allow all origins in development
        allow do
          origins Application::Config.access_control_allowed_origins
          resource '*',
              :headers => :any,
              :methods => [:get, :post, :delete, :put, :options]
        end
      end
      CODE
      end
    end

    def configure_environments
      Dir.glob('config/environments/*.rb').each do |file|
        prepend_to_file file, "require_relative '../config'\n"
        inject_into_file file, after: "Rails.application.configure do\n" do
          <<-CODE
  # Configure SMTP server
  Application::SMTP.configure(config)
          CODE
        end
      end
    end

    def configure_seeds_rb
      append_to_file "db/seeds.rb" do
        <<-CODE.strip_heredoc
      actions = ENV['ACTIONS'].present? ? ENV['ACTIONS'].split(',').map(&:squish) : nil
      Services::V1::System::CreateDefaultDataService.new(actions: actions).execute
        CODE
      end
    end

    ### ==== Gems setup ====

    def setup_minimal_gems
      setup_minimal_core_gems
      setup_minimal_deploy_gems
      setup_minimal_development_gems
      setup_minimal_staging_gems
    end

    def setup_minimal_core_gems
      gem 'pg'
      gem 'sequel'

      gem 'active_model_serializers', '0.9.3'
      gem 'bcrypt', '~> 3.1.7'
      gem 'colorize'
      gem 'database_cleaner'
      gem 'figaro'
      gem 'grape', '~> 0.12'
      gem 'grape-swagger'
      gem 'kaminari'
      gem 'newrelic_rpm'
      gem 'nifty_services', '~> 0.0.5'
      gem 'pry'
      gem 'puma'
      gem 'rack-contrib'
      gem 'rack-cors', require: 'rack/cors'
      gem 'rollbar'
    end

    def setup_minimal_deploy_gems
      # deploy specific
      gem_group :development do
        # pretty print for capistrano tasks
        gem 'airbrussh', :require => false

        gem 'capistrano',         require: false
        gem 'capistrano-bundler', require: false
        gem 'capistrano-hostmenu', require: false
        gem 'capistrano-rails',   require: false
        gem 'capistrano-rails-collection', require: false
        gem 'capistrano-rails-console', require: false

        gem 'capistrano-rvm',     require: false
        gem 'capistrano-safe-deploy-to', '~> 1.1.1', require: false
        gem 'capistrano-ssh-doctor', '~> 1.0'
        gem 'capistrano3-puma', require: false
      end
    end

    def setup_minimal_development_gems
      gem_group :development do
        gem 'brakeman', require: false
        gem 'letter_opener'
        gem 'rubocop', require: false
      end
    end

    def setup_minimal_staging_gems
      gem_group :staging, :test do
        gem 'factory_girl_rails', '~> 4.0'
        gem 'rspec-rails', '~> 3.0'
        gem 'shoulda-matchers', '~> 3.1'
        gem 'nyan-cat-formatter'
      end
    end

    ### ==== Setup routes ====

    # Send all requests to Grape
    def setup_minimal_routes
      route "mount API::Base => '/'"
    end

    def finish_minimal_template
      comment_lines 'Gemfile', /gem 'spring'/
    end
  end
end
module GrappiTemplate
  module Auth

    module_function
    def run_auth_template!
      extend Minimal

      # Copy all minimal template files
      run_minimal_template!

      say "Copying required files for auth template"
      copy_auth_files

      say "Injecting configurations on specific files"
      setup_auth_configurations

      say "Configurating gems"
      setup_auth_gems

      say "Configurating routes"
      setup_auth_routes

      say "Finished applying auth template"
    end

    ### ==== Copy files from this template to new generated Rails project ====

    def copy_auth_files
      copy_auth_concerns
      copy_auth_configs
      copy_auth_factories
      copy_auth_initializers
      copy_auth_helpers
      copy_auth_http_api_routes
      copy_auth_mailers
      copy_auth_migrations
      copy_auth_models
      copy_auth_serializers
      copy_auth_services
      copy_auth_specs
      copy_auth_workers
    end

    def copy_auth_concerns
      copy_auth_global_concerns
      copy_auth_user_concerns
    end

    def copy_auth_global_concerns
      copy_file_to File.join('models', 'concerns', 'user_named.rb'), File.join('app', 'model', 'concerns', 'user_named.rb')
    end

    def copy_auth_user_concerns
      [
        File.join('models', 'concerns', 'user_concerns', 'basic.rb'),
        File.join('models', 'concerns', 'user_concerns', 'auth.rb')
      ].each do |file|
        copy_file file, File.join('app', 'model', 'concerns', 'user_concerns', File.basename(file))
      end
    end

    def copy_auth_configs
      copy_file_to File.join('config', 'sidekiq.yml')
    end

    def copy_auth_factories
      [
        File.join('factories', 'authorizations.rb'),
        File.join('factories', 'origins.rb'),
        File.join('factories', 'users.rb')
      ].each do |file|
        copy_file_to File.join('spec', file)
      end
    end

    def copy_auth_initializers
      copy_file_to File.join('initializers', 'sidekiq.rb'), File.join('config', 'initializers', 'sidekiq.rb')
    end

    def copy_auth_helpers
      [
        File.join('api', 'helpers', 'auth_helpers.rb'),
        File.join('api', 'v1', 'helpers','auth_helpers.rb'),
        File.join('api', 'v1', 'helpers','user_auth_helpers.rb'),
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end


    def copy_auth_http_api_routes
      [
        File.join('api', 'v1', 'routes', 'users.rb'),
        File.join('api', 'v1', 'routes', 'users_auth.rb'),
        File.join('api', 'v1', 'routes', 'users_auth_social.rb'),
        File.join('api', 'v1', 'routes', 'users_me.rb'),
        File.join('api', 'v1', 'routes', 'users_me_cacheable.rb'),
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end

    def copy_auth_mailers
      copy_file_to File.join('mailers', 'users_mailer.rb'), File.join('app', 'mailers', 'users_mailer.rb')
      copy_directory File.join('views', 'users_mailer'), File.join('app', 'views', 'users_mailer')
    end

    def copy_auth_migrations
      # Basic migrations for authentication & user handling
      migrations = [
        'create_users',
        'create_authorization',
        'add_auth_columns_to_user',
        'create_origins',
        'change_unique_indexes_in_users'
      ]

      migrations_to_copy = Dir[File.join(BASE_DIR, 'migrations', '*.rb')].select do |file|
        # remove the extension and timestamp to be more easier to verify
        basename = File.basename(file, '.rb').sub(/\A\d+_(\w+)$/) { $1 }
        migrations.member?(basename)
      end.each do |file|
        copy_file_to File.join('migrations', File.basename(file)), File.join('db', 'migrate', File.basename(file))
      end
    end

    def copy_auth_models
      [
        File.join('models', 'authorization.rb'),
        File.join('models', 'user.rb'),
        File.join('models', 'origin.rb')
      ].each do |file|
        copy_file_to file , File.join('app', 'model', File.basename(file))
      end
    end

    def copy_auth_serializers
      copy_directory File.join('serializers', 'v1', 'auth'), File.join('lib', 'serializers', 'v1', 'auth')
      copy_directory File.join('serializers', 'v1', 'user'), File.join('lib', 'serializers', 'v1', 'user')
    end

    def copy_auth_services
      [
        File.join('services', 'v1', 'auth'),
        File.join('services', 'v1', 'users'),
        File.join('services', 'v1', 'concerns', 'users')
      ].each do |dir|
        copy_directory dir, File.join('lib', dir)
      end

      remove_services
    end

    def remove_services
      remove_file File.join('services', 'v1', 'users', 'notification_create_service.rb')
      remove_file File.join('services', 'v1', 'users', 'preferences_update_service.rb')
      remove_file File.join('services', 'v1', 'users', 'profile_image_update_service.rb')
    end

    def copy_auth_specs
      [
        File.join('models', 'authorization_spec.rb'),
        File.join('models', 'origin_spec.rb'),
        File.join('models', 'user_spec.rb')
      ].each do |file|
        copy_file_to File.join('spec', file)
      end
    end

    def copy_auth_workers
      [
        File.join('workers', 'v1', 'mail_delivery_worker.rb'),
        File.join('workers', 'v1', 'origin_create_worker.rb'),
        File.join('workers', 'v1', 'user_signup_update_worker.rb'),
        File.join('workers', 'v1', 'update_login_status_historic_worker.rb')
      ].each do |file|
        copy_file_to file, File.join('lib', file)
      end
    end

    ### ==== Configuration starts ====

    def setup_auth_configurations
      configure_auth_user_model
    end

    def configure_auth_user_model
      inject_into_file File.join('app', 'model', 'user.rb') , after: "#==markup==\n" do
        <<-CODE

  # Access Level Control
  include Accessable

  # add callbacks to generate user's username based on `name`, `first_name` and/or `last_name`
  include UserNamed

  # Basic user validations and setup
  include UserConcerns::Basic

  # User auth related setup (authentication, account confirmation, password recovery, account block)
  include UserConcerns::Auth

        CODE
      end
    end


    ### ==== Gem setup ====

    def setup_auth_gems
      setup_auth_core_gems
      setup_auth_deploy_gems
    end

    def setup_auth_core_gems
      # just to keep alphabetical organization in Gemfile
      inject_into_file 'Gemfile', after: "gem 'database_cleaner'\n" do
        <<-CODE
gem 'faker'
        CODE
      end

      inject_into_file 'Gemfile', before: "gem 'rollbar'\n" do
        <<-CODE
gem 'redis-namespace'
gem 'sidekiq'
gem 'sinatra', require: false
      CODE
      end
    end

    def setup_auth_deploy_gems
      inject_into_file 'Gemfile', after: "gem 'capistrano-safe-deploy-to', '~> 1.1.1', require: false\n" do
        <<-CODE
    gem 'capistrano-sidekiq', require: false
        CODE
      end
    end

    ### ==== Routes setup ====

    def setup_auth_routes
      setup_auth_sidekiq_routes
      mount_auth_grape_endpoints
    end

    def setup_auth_sidekiq_routes
      prepend_to_file File.join("config","routes.rb") do
        <<-CODE
  require 'sidekiq/web'
        CODE
      end

      inject_into_file File.join("config","routes.rb"), after: "mount API::Base => '/'\n" do
        <<-CODE

  # Configure sidekiq basic auth
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Application::Config.sidekiq_username && password == Application::Config.sidekiq_password
  end
  # Mount sidekiq Web UI at /sidekiq
  mount Sidekiq::Web, at: '/sidekiq'

        CODE
      end
    end

    def mount_auth_grape_endpoints
      base_file = File.join('app','grape','api','base.rb')
      v1_base_file = File.join('app','grape','api','v1','base.rb')

      inject_into_file base_file, before: "mount V1::Routes::Heartbeat\n" do
        <<-CODE
    helpers API::Helpers::AuthHelpers
        CODE
      end

      inject_into_file v1_base_file, before: "mount V1::Routes::Heartbeat\n" do
        <<-CODE
    helpers API::V1::Helpers::AuthHelpers
        CODE
      end

      inject_into_file v1_base_file, after: "mount V1::Routes::Heartbeat\n" do
        <<-CODE

      mount V1::Routes::Users
      mount V1::Routes::UsersAuth
      mount V1::Routes::UsersAuthSocial
      mount V1::Routes::UsersMe
      mount V1::Routes::UsersMeCacheable

        CODE
      end
    end
  end
end


module GrappiTemplate
  module Complete
    include Helpers

    module_function

    def run_complete_template!
      extend Full

      # Copy all minimal + auth + full template files
      run_full_template!

      say "Copying required files for complete template"
      copy_complete_files

      say "Injecting configurations on specific files"
      setup_complete_configurations

      say "Configurating gems"
      setup_complete_gems

      say "Configurating routes"
      setup_complete_routes

      say "Finished applying complete template"
    end


    ### ==== Copy files from this template to new generated Rails project ====

    def copy_complete_files
      copy_complete_concerns
      copy_complete_initializers
      copy_complete_helpers
      copy_complete_http_api_routes
      copy_complete_services
      copy_complete_uploaders
    end

    def copy_complete_concerns
      [
        File.join('models', 'concerns', 'user_concerns', 'preferences.rb'),
        File.join('models', 'concerns', 'user_concerns', 'profile_image.rb'),
      ].each do |file|
        copy_file file, File.join('app', 'model', 'concerns', 'user_concerns', File.basename(file))
      end
    end

    def copy_complete_initializers
      [
        File.join('initializers', 'app_cache.rb'),
        File.join('initializers', 'carrierwave.rb'),
        File.join('initializers', 'piet.rb'),
      ].each do |file|
        copy_file_to file, File.join('config', file)
      end
    end

    def copy_complete_helpers
      [
        File.join('api', 'helpers', 'cache', 'cache_dsl.rb'),
        File.join('api', 'helpers', 'cache', 'cache_helpers.rb'),
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', 'helpers', File.basename(file))
      end
    end

    def copy_complete_http_api_routes
      [
        File.join('api', 'v1', 'routes', 'users_me_preferences.rb'),
        File.join('api', 'v1', 'routes', 'users_me_update_image.rb')
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end

    def copy_complete_services
      [
        File.join('services', 'v1', 'users', 'preferences_update_service.rb'),
        File.join('services', 'v1', 'users', 'profile_image_update_service.rb')
      ].each do |file|
        copy_file_to file, File.join('lib', file)
      end
    end

    ### ==== Configuration starts ====

    def setup_complete_configurations
      configure_complete_environments
      configure_complete_user_model
    end

    def configure_complete_environments
      Dir.glob('config/environments/*.rb').each do |file|
        prepend_to_file file, "require_relative '../config'\n"
        inject_into_file file, after: "Application::SMTP.configure(config)\n" do
          <<-CODE.strip_heredoc
            Application::Cache.configure(config)
          CODE
        end
      end
    end

    def configure_complete_user_model
      inject_into_file File.join('app', 'model', 'user.rb') , after: "#==markup==\n" do
        <<-CODE.strip_heredoc
          # User profile images
          include UserConcerns::ProfileImage
        CODE
      end
    end

    def copy_complete_uploaders
      copy_directory 'uploaders', File.join('app', 'uploaders')
    end


    ### ==== Gems setup ====

    def setup_complete_gems
      setup_complete_core_gems
    end

    def setup_complete_core_gems
      # just to keep alphabetical organization in Gemfile
      inject_into_file 'Gemfile', after: "gem 'bcrypt', '~> 3.1.7'\n" do
        <<-CODE.strip_heredoc
          gem 'carrierwave', require: 'carrierwave'
          gem 'carrierwave-sequel', require: 'carrierwave/sequel'
        CODE
      end

      inject_into_file 'Gemfile', after: "gem 'colorize'\n" do
        "gem 'dalli'"
      end

      inject_into_file 'Gemfile', after: "gem 'figaro'\n" do
        "gem 'fog'"
      end

      inject_into_file 'Gemfile', after: "gem 'grape-swagger'\n" do
        "gem 'mini_magick'"
      end

      inject_into_file 'Gemfile', after: "gem 'nifty_services', '~> 0.0.5'\n" do
      <<-CODE.strip_heredoc
        gem 'piet'
        gem 'png_quantizator' # piet it'self already include this gem, but just for sure
      CODE
      end

      inject_into_file 'Gemfile', after: "gem 'sidekiq'\n" do
        "gem 'simplified_cache', git: 'git@bitbucket.org:fidelisrafael/simplified_cache.git', branch: 'master'"
      end
    end

    ### ==== Routes setup ====

    def setup_complete_routes
      mount_complete_grape_endpoints
    end

    def mount_complete_grape_endpoints
      v1_base_file = File.join('app','grape','api','v1','base.rb')

      inject_into_file v1_base_file, after: "mount V1::Routes::UsersMeCacheable\n" do
        <<-CODE.strip_heredoc
          mount V1::Routes::UsersMePreferences
          mount V1::Routes::UsersMeUpdateImage
        CODE
      end

      inject_into_file v1_base_file, before: "version 'v1'\n" do
        <<-CODE.strip_heredoc
          include API::Helpers::CacheDSL
          helpers API::Helpers::CacheHelpers
        CODE
      end
    end

  end
end
module GrappiTemplate
  module Full

    module_function
    def run_full_template!
      extend Auth

      # Copy all minimal + auth template files
      run_auth_template!

      say "Copying required files for full template"
      copy_full_files

      say "Injecting configurations on specific files"
      setup_full_configurations

      say "Configurating gems"
      setup_full_gems

      say "Configurating routes"
      setup_full_routes

      say "Finished applying full template"
    end

    ### ==== Copy files from this template to new generated Rails project ====

    def copy_full_files
      copy_full_concerns
      copy_full_initializers
      copy_full_helpers
      copy_full_http_api_routes
      copy_full_models
      copy_full_services
      copy_full_workers
    end

    def copy_full_concerns
      [
        File.join('models', 'concerns', 'user_concerns', 'address.rb'),
        File.join('models', 'concerns', 'user_concerns', 'notifications.rb'),
      ].each do |file|
        copy_file file, File.join('app', 'model', 'concerns', 'user_concerns', File.basename(file))
      end
    end

    def copy_full_initializers
      [
        File.join('initializers', 'parse_client.rb'),
        File.join('initializers', 'services_notification_setup.rb'),
        File.join('initializers', 'uniqueness_validator.rb')
      ].each do |file|
        copy_file_to file, File.join('config', 'initializers', file)
      end
    end

    def copy_full_helpers
      [
        File.join('api', 'v1', 'helpers', 'cities_helpers.rb'),
        File.join('api', 'v1', 'helpers', 'states_helpers.rb'),
        File.join('api', 'v1', 'helpers', 'user_notifications_helpers.rb'),
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end

    def copy_full_http_api_routes
      [
        File.join('api', 'v1', 'routes', 'cities.rb'),
        File.join('api', 'v1', 'routes', 'states.rb'),
        File.join('api', 'v1', 'routes', 'users_me_devices.rb'),
        File.join('api', 'v1', 'routes', 'users_me_notifications.rb'),
      ].each do |file|
        copy_file_to file, File.join('app', 'grape', file)
      end
    end

    def copy_full_models
      [
        File.join('models', 'city.rb'),
        File.join('models', 'state.rb'),
        File.join('models', 'notification.rb'),
        File.join('models', 'user_device.rb')
      ].each do |file|
        copy_file_to file , File.join('app', 'model', File.basename(file))
      end
    end

    def copy_auth_serializers
      copy_directory File.join('serializers', 'v1', 'address'), File.join('lib', 'serializers', 'v1', 'address')
      copy_directory File.join('serializers', 'v1', 'states_cities'), File.join('lib', 'serializers', 'v1', 'address')
      copy_directory File.join('serializers', 'v1', 'notification'), File.join('lib', 'serializers', 'v1', 'notification')
    end

    def copy_full_services
      [
        File.join('services', 'v1', 'users', 'notification_create_service.rb'),
      ].each do |file|
        copy_file_to file, File.join('lib', file)
      end

      copy_directory File.join('services', 'v1', 'addresses'), File.join('lib', 'services', 'v1', 'addresses')
      copy_directory File.join('services', 'v1', 'parse'), File.join('lib', 'services', 'v1', 'parse')
    end

    def copy_full_workers
      [
        File.join('workers', 'v1', 'notification_create_worker.rb'),
        File.join('workers', 'v1', 'parse_device_create_worker.rb'),
        File.join('workers', 'v1', 'parse_device_delete_worker.rb'),
        File.join('workers', 'v1', 'parse_device_save_worker.rb'),
        File.join('workers', 'v1', 'push_notification_delivery_worker.rb')
      ].each do |file|
        copy_file_to file, File.join('lib', file)
      end
    end

    ### ==== Configuration starts ====

    def setup_full_configurations
      configure_full_user_model
    end

    def configure_full_user_model
      inject_into_file File.join('app', 'model', 'user.rb') , after: "class User < ActiveRecord::Base\n" do
        <<-CODE.strip_heredoc
          # soft delete
          acts_as_paranoid
        CODE
      end

      inject_into_file File.join('app', 'model', 'user.rb') , after: "#==markup==\n" do
        <<-CODE.strip_heredoc
          # Notifications
          include UserConcerns::Notifications
        CODE
      end
    end


    ### ==== Gems setup ====

    def setup_full_gems
      setup_full_core_gems
    end

    def setup_full_core_gems
      inject_into_file 'Gemfile', after: "gem 'nifty_services', '~> 0.0.5'\n" do
      <<-CODE.strip_heredoc
        gem 'paranoia', '~> 2.0.0'
        gem 'parse-ruby-client', git: 'https://github.com/adelevie/parse-ruby-client.git'
      CODE
      end
    end

    ### ==== Routes setup ====

    def setup_full_routes
      mount_full_grape_endpoints
    end

    def mount_full_grape_endpoints
      v1_base_file = File.join('app','grape','api','v1','base.rb')

      inject_into_file v1_base_file, after: "mount V1::Routes::UsersMeCacheable\n" do
        <<-CODE.strip_heredoc
          mount V1::Routes::Cities
          mount V1::Routes::States
          mount V1::Routes::UsersMeNotifications
        CODE
      end
    end

  end
end
module GrappiTemplate

  GRRAPI_FLAG = "--grrapi-template-mode"

  def init_grrapi_template_action!(argv)
    application_types = [
      'minimal',
      'auth',
      'complete',
      'full'
    ]


    default_app_type = 'minimal'
    current_app_type = argv.find {|v| v.match(/#{GRRAPI_FLAG}=(\w+)/) }

    application_mode = (current_app_type ? (current_app_type.match(/#{GRRAPI_FLAG}=(\w+)/) && $1)  : default_app_type ).downcase

    raise "Invalid application mode #{application_mode}" unless application_types.member?(application_mode)

    extend GrappiTemplate.const_get(application_mode.capitalize)

    self.send("run_#{application_mode}_template!")
  end
end

extend GrappiTemplate

init_grrapi_template_action!(ARGV)
